import Head from 'next/head'

const page = () => (
  <div>
    <Head>
      <title>Sarah Bonavia - CV</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main>
      <h1>
        CV
      </h1>
    </main>
  </div>
)

export default page
