import Head from 'next/head'
import Link from 'next/link'

const page = () => (
  <div>
    <Head>
      <title>Sarah Bonavia</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main>
      <h1>
        Making a
        difference
        with all
        my skills.
      </h1>

      <section>
        <header><h1>This is me</h1></header>

        <p>
          I’m a swiss-italian 43 years old woman based in Zürich. I love everything that has to do with  Visual Communication, Art, Film and I feel a true devotion for social engagement. 
          I love working with people, specially if they have the same passion and values I have for what they do.
        </p>

        <ul>
          <li>Visual Strategy</li>
          <li>Graphic Design</li>
          <li>Social Work</li>
          <li>Video Production</li>
          <li>Branding</li>
          <li>Social Media</li>
          <li>Human Rights</li>
          <li>Events Content</li>
          <li>Marketing</li>
          <li>Creative Initiatives</li>
        </ul>

        <Link href="/cv">See my CV</Link>
      </section>

      <section>
        <header><h1>Looking for an
          opportunity to
          provide a change</h1></header>

        <p>
          I want to make a difference. And I can make a difference.
        </p>
        <p>
          I have worked as a graphic designer for various brands and agencies in
          print media, packaging design, development and corporate design.
          That’s good and exciting. But I am looking for more.
        </p>
        <p>
          I would like to grow, develop in a team, get the best out of myself -
          make a difference. With more than 15 years of professional experience
          in a wide range of activities, I want to bring the whole range of
          skills to my work. As a visual designer, communication strategist,
          social worker and multilingual person I aim to work for projects that
          have a meaning, a purpose.
        </p>
        <p>
          Are you interested in working together? I would love to hear from you.
        </p>

        <Link href="/contact">Get in Touch</Link>
      </section>


      <section>
        <header><h1>Collaborations{'&'}Volunteering</h1></header>

        <p>
          I am and have been collaborating with Verein Zürich City Card (SPAZ),
          ExpoTranskultur (Zurich), Bio Ticino, Terra Verde Bio-Gourmet
          (Zurich), Body Learning (Zürich), La Festuca (Biasca, Ticino),
          Fabbrica di Zurigo (Zurich), Amal Center (Ioannina, Greece), Punto
          d’Incontro (Zurich), Marea Granate Zürich, Integrationsförderung der
          Stadt Zürich, PBI - Peace Brigades International (Barcelona) among
          others.
        </p>
      </section>
    </main>
  </div >
)

export default page
