import Head from 'next/head'

const page = () => (
    <div>
      <Head>
        <title>Sarah Bonavia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Making a
          difference
          with all
          my skills.
        </h1>

        <section>
          <header><h1>This is me</h1></header>

          <p>
            I’m a swiss-italian 43 years old woman based in Zürich. I love everything that has to do with  Visual Communication, Art, Film and I feel a true devotion for social engagement. 
            I love working with people, specially if they have the same passion and values I have for what they do.
          </p>

          <ul>
            <li>Visual Strategy</li>
            <li>Graphic Design</li>
            <li>Social Work</li>
            <li>Video Production</li>
            <li>Branding</li>
            <li>Social Media</li>
            <li>Human Rights</li>
            <li>Events Content</li>
            <li>Marketing</li>
            <li>Creative Initiatives</li>
          </ul>
        </section>
      </main>
    </div>
  )

  export default page
