import Head from 'next/head'

const page = () => (
  <div>
    <Head>
      <title>Sarah Bonavia - Work</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main>
      <h1>
        Work{'&'}Experiences
      </h1>

      <nav>
        <ul>
          <li>All</li>
          <li>Corporate</li>
          <li>Packaging</li>
          <li>Events</li>
          <li>Social Work</li>
        </ul>
      </nav>
    </main>
  </div>
)

export default page
