import Head from 'next/head'
import Image from 'next/image'
import terraverdesalse from '../public/work/terraverde-salse.jpg'


const page = () => (
  <div>
    <Head>
      <title>Sarah Bonavia - Work</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main>
      <h1>
        Work{'&'}Experiences
      </h1>

      <nav>
        <ul>
          <li>All</li>
          <li>Corporate</li>
          <li>Packaging</li>
          <li>Events</li>
          <li>Social Work</li>
        </ul>
      </nav>
      <section>
        <Image src={terraverdesalse} alt="terra verde salse" ></Image>
        <h2>
          La Festuca
          <small>Biologica tradizione ticinese dal 1982</small>
        </h2>
        <p>Blah blah</p>
      </section>
    </main>
  </div>
)

export default page
